- name: catalogue configuration
  hosts: catalogue
  become: yes
  tasks:
    - name: disabling nodejs
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enabling required version of nodejs
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: installing nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
      
    - name: creating systemuser
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        system: yes
        home: /app

    - name: creating app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: downloading the code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp/catalogue.zip

    - name: extracting the code
      ansible.builtin.unarchive:
        src: /tmp/catalouge.zip
        dest: /app
        